var DepositPoint = {
    id: String,
    type: String,
    serialNumber: String,
    refSortingType: String,
    description: String,
    refCollectionPointType: String,
    storedWastOrigin: String,
    address: String,
    fillingLevel: String,
    cargoWeight: String,
    temperature: String,
    methaneConcentration: String,
    regulation: String,
    responsible: String,
    owner: String,
    dateServiceStarted: String,
    dateLastEmptying: String,
    nextActuationDeadline: String,
    actuationHours: String,
    openingHours: String,
    dateLastCleaning: String,
    nextCleaningDeadline: String,
    refCollectionPointlsle: String,
    status: String,
    color: String,
    image: String,
    annotations: String,
    areaServed: String,
    dateModified: String,
    refDevice: String,
    coordxUTM: String,
    coordyUTM: String,
    POINT_X: String,
    POINT_Y: String,
}

module.exports = DepositPoint;